apiVersion: v1
kind: Service
metadata:
  name: hello-world-api
spec:
  selector:
    app: hello-world-api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer